### ISSUE TITLE
这个应用可以更酷～

### ISSUE THREAD

**Issue by alsotang** [hit9/GhResume#1]
我没事瞎扯淡哈～

先来看看这里：http://alsotang.github.io/ 还有这里 http://sneezry.github.io/

如果你哪天有兴趣玩前端 MVC 框架的话，可以把这个项目迁到 github pages 上面去练练手～

用 Ember.js 的话，静态 HTML 一样可以响应 querystring。而且 github 的 api 是可以通过 jsonp 调用的。

**Comment by hit9** [comment]
你的意思是去掉url后跟的 .`?arg` ? 不知道我理解了你的意思没有，我不是专业搞前端的....

**Comment by alsotang** [comment]
不是的…我的意思是 这个项目目前需要后端的处理 而我见过一个完全靠前端代码完成的类似的 github 简历生成项目。放在 github.io 上

如果改成纯前端方式的话，querystring 的获取是 resume.html?#/hit9 或者 resume.html?#!hit9
这样的形式。resume.html 载入完成后，里面的 JS 去读取这些锚点，然后 jsonp 去 github 取。

发自我的 iPhone

在 2013-5-16，18:36，Wang Chao notifications@github.com 写道：

你的意思是去掉url后跟的 .?arg ? 不知道我理解了你的意思没有，我不是专业搞前端的....

—
Reply to this email directly or view it on
GitHubhttps://github.com/hit9/GhResume/issues/1#issuecomment-17993520
.

**Comment by hit9** [comment]
哦哦，现在的GhResume就是这个情况啊。这个Repo就是在Github page上。也是用纯前端的方式在抓Github API. 也是JSONP的方式在跨域。

**Comment by alsotang** [comment]
噢……不好意思……我脑袋短路才提的这个 issue……

发自我的 iPhone

在 2013-5-16，19:35，Wang Chao notifications@github.com 写道：

哦哦，现在的GhResume就是这个情况啊。这个Repo就是在Github page上。也是用纯前端的方式在抓Github API.
也是JSONP的方式在跨域。

—
Reply to this email directly or view it on
GitHubhttps://github.com/hit9/GhResume/issues/1#issuecomment-17995750
.

**Comment by hit9** [comment]
没事 :) 你同学知乎有消息了吗

**Comment by alsotang** [comment]
应该是还没，等消息中吧..

2013/5/16 Wang Chao notifications@github.com
